image: ${BASE_IMAGE}

services:
  - docker:dind

stages:
  - build-prerequisites
  - build
  - test
  - release
  - provision

before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}

variables:
  BASE_IMAGE: ${CI_REGISTRY_IMAGE}/docker-build:${CI_COMMIT_REF_SLUG}

build-base-images:
  image: docker
  stage: build-prerequisites
  script:
    - docker build -t ${BASE_IMAGE} gitlab/dockerfiles/docker-build
    - docker push ${BASE_IMAGE}
  tags:
    - docker
  only:
    - merge_requests

build-ui:
  stage: build
  script:
    - make build-ui
  only:
    - merge_requests

build-crawler:
  stage: build
  script:
    - make build-crawler
  only:
    - merge_requests

test-ui:
  stage: test
  script:
    - make test-ui
  only:
    - merge_requests

test-crawler:
  stage: test
  script:
    - make test-crawler
  only:
    - merge_requests

release-ui:
  stage: release
  script:
    - make release-ui
  only:
    - merge_requests

release-crawler:
  stage: release
  script:
    - make release-crawler
  only:
    - merge_requests

provision-staging-infra:
  stage: provision
  script:
    - make infra-vars
    - make infra-initialization
    - TF_WORKSPACE=stage make infra-workspace
    - make infra-planning
    - make infra-applying
  only:
    - master

provision-production-infra:
  stage: provision
  script:
    - make infra-vars
    - make infra-initialization
    - TF_WORKSPACE=stage make infra-workspace
    - make infra-planning
    - make infra-applying
  only:
    - ^release-
  except:
    - branches
