image: ${BASE_IMAGE}

services:
  - docker:dind

stages:
  - build-prerequisites
  - build
  - test
  - release

before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}

variables:
  BASE_IMAGE: ${CI_REGISTRY_IMAGE}/dind:${CI_COMMIT_REF_SLUG}

build-base-images:
  image: docker
  stage: build-prerequisites
  script:
    - docker build -t ${BASE_IMAGE} gitlab/dockerfiles/dind
    - docker push ${BASE_IMAGE}
  tags:
    - docker

build-ui:
  stage: build
  script:
    - make build-ui

build-crawler:
  image: ${BASE_IMAGE}
  stage: build
  script:
    - make build-crawler

test-ui:
  image: ${BASE_IMAGE}
  stage: test
  script:
    - make test-ui

test-crawler:
  image: ${BASE_IMAGE}
  stage: test
  script:
    - make test-crawler

release-ui:
  image: ${BASE_IMAGE}
  stage: release
  script:
    - make release-ui

release-crawler:
  image: ${BASE_IMAGE}
  stage: release
  script:
    - make release-crawler
