image: ${BASE_IMAGE}

services:
  - docker:dind

stages:
  - build-prerequisites
  - build
  - test
  - release

before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}

variables:
  BASE_IMAGE: ${CI_REGISTRY_IMAGE}/docker-build:${CI_COMMIT_REF_SLUG}

build-base-images:
  image: docker
  stage: build-prerequisites
  script:
    - docker build -t ${BASE_IMAGE} gitlab/dockerfiles/docker-build
    - docker push ${BASE_IMAGE}
  tags:
    - docker

build-ui:
  stage: build
  script:
    - make build-ui

build-crawler:
  stage: build
  script:
    - make build-crawler

build-infra:
  stage: build
  script:
    - cd infra/terraform
    - echo "project_id = ${GCP_PROJECT_ID}" >> vars.auto.tfvar
    - echo "credentials = ${GCP_CREDENTIALS_FILE}" >> vars.auto.tfvar
    - echo "ssh_key = ${GCP_INSTANCE_PUBLIC_KEY}" >> vars.auto.tfvar
    - terraform init -input=false
    - terraform plan -input=false

test-ui:
  stage: test
  script:
    - make test-ui

test-crawler:
  stage: test
  script:
    - make test-crawler

release-ui:
  stage: release
  script:
    - make release-ui

release-crawler:
  stage: release
  script:
    - make release-crawler
